---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./extra-resources/rag-manager.Namespace.yaml
  - ./extra-resources/rag-manager-pg.rag-namespace.Cluster.yaml
  - ./resources/data-source-manager-migration-up.rag-manager.Job.yaml
  - ./resources/data-source-manager.rag-manager.Deployment.yaml
  - ./resources/data-source-manager.rag-manager.Service.yaml
