apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./extra-resources/go-template.Namespace.yaml
  - ./resources/go-template-migrate.go-template.Job.yaml
  - ./resources/go-template.go-template.Deployment.yaml
  - ./resources/go-template.go-template.Service.yaml

images:
  - name: application-image
    newName: docker.io/fr33dman/go-template
    newTag: latest
